theme: jekyll-theme-cayman
title: Welcome
description: This is the homepage of Adam Gilbert, Associate Professor of Mathematics at Southern New Hampshire University. I am interested in data science, discrete mathematics, and developing open educational resources (OER). You'll find information on these topics as well as the courses I regularly teach scattered across these pages. If you find anything here to be interesting or useful, please e-mail me.
